### ISSUE TITLE
Is it possible to force the alignment?

### ISSUE THREAD

**Issue by naxmefy** [inkdropapp/inkdrop-math#8]
that would be a nice feature.

Normally markdown behaves with "left alignment" but here (except inline) it is forced to use centered

```
$$
2(x+5)-7 = 3(x-2)
\\
2x+10-7 = 3x-6
\\
9 = x
$$
```

**Comment by craftzdog** [comment]
You can do that by applying a custom CSS like so in your [styles.less](https://docs.inkdrop.app/manual/style-tweaks):

```css
.katex-display > .katex {
    text-align: left;
}
```
